<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.nervousync</groupId>
        <artifactId>cache-parent</artifactId>
        <version>1.2.0</version>
    </parent>
    <artifactId>cache-core</artifactId>
    <packaging>jar</packaging>
    <name>Cache Utilities Collections Core Package</name>
    <url>https://nervousync.org/projects/cache/core/index.shtml</url>
    <description>Cache utilities collections core package, development by Nervousync Studio (NSYC)</description>
    <dependencies>
        <dependency>
            <groupId>org.nervousync</groupId>
            <artifactId>cache-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>