<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.nervousync</groupId>
        <artifactId>cache-parent</artifactId>
        <version>1.2.0-SNAPSHOT</version>
    </parent>
    <artifactId>cache-bom</artifactId>
    <packaging>pom</packaging>
    <name>Nervousync Cache Utility BOM</name>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.nervousync</groupId>
                <artifactId>cache-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.nervousync</groupId>
                <artifactId>cache-all</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.nervousync</groupId>
                <artifactId>cache-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.nervousync</groupId>
                <artifactId>cache-jedis</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.nervousync</groupId>
                <artifactId>cache-lettuce</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.nervousync</groupId>
                <artifactId>cache-redisson</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.nervousync</groupId>
                <artifactId>cache-xmemcached</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.nervousync</groupId>
                <artifactId>cache-test</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>