<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.nervousync</groupId>
        <artifactId>cache-parent</artifactId>
        <version>1.2.0-SNAPSHOT</version>
    </parent>
    <artifactId>cache-api</artifactId>
    <packaging>jar</packaging>
    <name>Cache utilities collections API package</name>
    <url>https://nervousync.org/projects/cache/api/index.shtml</url>
    <description>Cache utilities collections API package, development by Nervousync Studio (NSYC)</description>
    <dependencies>
        <dependency>
            <groupId>org.nervousync</groupId>
            <artifactId>utils-all</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>
    </dependencies>
</project>